name: .NET Build and Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore NugetMcpCli.sln
      - name: Build
        run: dotnet build NugetMcpCli.sln --no-restore
      - name: Test
        run: dotnet test NugetMcpCli.sln --no-build

